spring:
  application:
    name: carInfo
  profiles:
    active: dev
  config:
    import: nacos:carInfo-dev.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        group: DEFAULT_GROUP
      config:
        file-extension: yml
        group: DEFAULT_GROUP
dubbo:
  application:
    name: car-info-service

    check-serializable: false

    serialize-check-status: WARN
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20880


mybatis:
  mapper-locations: classpath:mapper/*.xml
