spring:
  application:
    name: warn
  profiles:
    active: dev
  config:
    import: nacos:warn-dev.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        group: DEFAULT_GROUP
      config:
        file-extension: yml
        group: DEFAULT_GROUP


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xm.bms.user.domain
dubbo:
  application:
    name: car-info-service

    check-serializable: false

    serialize-check-status: WARN
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20881
    serialization: fastjson2

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: signal-producer
