spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: nacos:gateway-dev.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        group: DEFAULT_GROUP
      config:
        file-extension: yml
        group: DEFAULT_GROUP

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xm.bms.user.domain
